/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.DonationCentreInterface.DonarLoginPages.DonarAdminBankLoginPages;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.DonationCentre.UserDonor;
import finalprojectBackend.Enterprise.DonationCentre.BankDonor;
import finalprojectBackend.Organization.AssignmentDonation;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author shreyas purkar
 */
public class DonationCentreAdminItemDonate extends javax.swing.JPanel {

    /**
     * Creates new form DonationCentreAdminItemDonate
     */
    boolean ValidationStatus = true;
    boolean validationCheck = true;
    MainJFrameForm MainLoginPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    BankDonor donorBank;

    public DonationCentreAdminItemDonate(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, BankDonor donarbank) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.donorBank = donarbank;

        for (UserDonor pa : operatingSystem.getUserDonorDirectory()) {
            System.out.println("DonorAdminDonateOrgan" + pa.getBankDonorName());
            if (pa.getBankDonorName().equals(donarbank.getNameEnterprise())) {
                donar_txt.addItem(pa.getpName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_lbl = new javax.swing.JLabel();
        donar_lbl = new javax.swing.JLabel();
        item_lbl = new javax.swing.JLabel();
        itemname_txt = new javax.swing.JTextField();
        itemname_lbl = new javax.swing.JLabel();
        cat_lbl = new javax.swing.JLabel();
        status_lbl = new javax.swing.JLabel();
        status_cmb = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        donar_txt = new javax.swing.JComboBox<>();
        txtUnits = new javax.swing.JTextField();
        cat_txt = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(169, 146, 125));

        title_lbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("Add Entity Details");

        donar_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        donar_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donar_lbl.setText("Donor Name:");

        item_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        item_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        item_lbl.setText("Weight (LB):");

        itemname_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        itemname_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemname_lbl.setText("Item Name:");

        cat_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cat_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cat_lbl.setText("Category:");

        status_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        status_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_lbl.setText("Status:");

        status_cmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        status_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        btn_save.setBackground(new java.awt.Color(102, 102, 102));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("Save");
        btn_save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        donar_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        donar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donar_txtActionPerformed(evt);
            }
        });

        cat_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper", "Electronics", "Metal", "Not Identifiable" }));
        cat_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(itemname_lbl)
                                    .addGap(85, 85, 85)
                                    .addComponent(itemname_txt))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(donar_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85)
                                    .addComponent(donar_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(status_lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(status_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(item_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cat_lbl))
                                    .addGap(85, 85, 85)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(cat_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cat_lbl, donar_lbl, item_lbl, itemname_lbl, status_lbl});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {donar_txt, itemname_txt, status_cmb, txtUnits});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donar_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemname_lbl)
                    .addComponent(itemname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_lbl)
                    .addComponent(cat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_lbl)
                    .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status_lbl)
                    .addComponent(status_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cat_lbl, donar_lbl, item_lbl, itemname_lbl, status_lbl});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {donar_txt, itemname_txt, status_cmb, txtUnits});

    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        try {
            if (EmpytyFieldValidation()) {
                if (RegexValidation()) {
                    AssignmentDonation de = new AssignmentDonation();
                    de.setEntityName(itemname_txt.getText().toString());
                    de.setDonEnterpriseClass(donorBank);
                    Random rand = new Random();
                    de.setUserId(String.format("%04d", rand.nextInt(10000)));
                    de.setCategory(cat_txt.getSelectedItem().toString());
                    de.setUnits(Double.parseDouble(txtUnits.getText()));

                    de.setDonRecepient(operatingSystem.getReceiverByUserName(donar_txt.getSelectedItem().toString()));
                    de.setStatusDonation(status_cmb.getSelectedItem().toString());

                    operatingSystem.addDonationAssignment(de);

                    dB4OUtility.storeSystem(operatingSystem);

                    JOptionPane.showMessageDialog(this, "Entity details added.");
                } else {
                    JOptionPane.showMessageDialog(this, "Some rrror in entered data.Please check over the fields to know more.");
                    validationCheck = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data can't be empty. Please check over the fields to know more.");
                ValidationStatus = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Donation center admin not registered, Try again");
            ValidationStatus = true;
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void donar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donar_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donar_txtActionPerformed

    private void cat_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel cat_lbl;
    private javax.swing.JComboBox<String> cat_txt;
    private javax.swing.JLabel donar_lbl;
    private javax.swing.JComboBox<String> donar_txt;
    private javax.swing.JLabel item_lbl;
    private javax.swing.JLabel itemname_lbl;
    private javax.swing.JTextField itemname_txt;
    private javax.swing.JComboBox<String> status_cmb;
    private javax.swing.JLabel status_lbl;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JTextField txtUnits;
    // End of variables declaration//GEN-END:variables

    private boolean EmpytyFieldValidation() {
        if (itemname_txt.getText().equals(null) || itemname_txt.getText().trim().isEmpty()) {
            itemname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            itemname_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus = false;
        }
        if (!itemname_txt.getText().equals(null) && !itemname_txt.getText().trim().isEmpty()) {
            itemname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            itemname_txt.setToolTipText(null);
        }

        if (txtUnits.getText().equals(null) || txtUnits.getText().trim().isEmpty()) {
            txtUnits.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtUnits.setToolTipText("This Field Cannot be empty");
            ValidationStatus = false;
        }
        if (!txtUnits.getText().equals(null) && !txtUnits.getText().trim().isEmpty()) {
            txtUnits.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            txtUnits.setToolTipText(null);
        }
        return ValidationStatus;
    }

    private boolean RegexValidation() {
        if (!itemname_txt.getText().matches("^[a-zA-Z ]+$")) {
            itemname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            itemname_txt.setToolTipText("Please enter only characters and space.");
            validationCheck = false;
        } else {
            itemname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            itemname_txt.setToolTipText(null);
        }

        if (!txtUnits.getText().matches("^\\d+(\\.\\d+)?$")) {
            txtUnits.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txtUnits.setToolTipText("Please enter an integer");
            validationCheck = false;
        } else {
            txtUnits.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
            txtUnits.setToolTipText(null);
        }
        return validationCheck;
    }
}
