/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.UpcyclingCenterInterface.LoginPage.NGOAdminLoginPages;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.UpcyclingCenter.UpcyclingCenterClass;
import finalprojectBackend.Enterprise.UpcyclingCenter.UpcyclingCenterManager;
import finalprojectUserInterface.MainJFrameForm;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Neelabh
 */
public class AdminPageForNGOManager extends javax.swing.JPanel {

    /**
     * Creates new form AdminPageForNGOManager
     */
    MainJFrameForm MainLoginPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    UpcyclingCenterClass ngo;

    public AdminPageForNGOManager(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, UpcyclingCenterClass h) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.ngo = h;
        populateManagerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_1 = new javax.swing.JTable();
        manager_lbl = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 146, 125));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "User Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 1010, 550));

        manager_lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manager_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manager_lbl.setText("Manage NGO Managers");
        add(manager_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 290, 60));

        delete_btn.setBackground(new java.awt.Color(102, 102, 102));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 720, 110, 40));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) table_1.getModel();
        String doctorUName = model.getValueAt(selectedRow, 1).toString();
        System.out.println(" manager uname: " + doctorUName);
        operatingSystem.deleteUpcyclingCenterManager(doctorUName);
        dB4OUtility.storeSystem(operatingSystem);
        populateManagerTable();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void populateManagerTable() {
        DefaultTableModel model = (DefaultTableModel) table_1.getModel();
        model.setRowCount(0);

        for (UpcyclingCenterManager d : operatingSystem.getUpcyclingCenterManagerDirectory()) {

            if (d.getNGOName().equals(ngo.getNameEnterprise())) {
                Object[] row = new Object[3];
                row[0] = d.getNamePerson();
                row[1] = d.getpName();
                row[2] = d.getAddr();
                model.addRow(row);

            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manager_lbl;
    private javax.swing.JTable table_1;
    // End of variables declaration//GEN-END:variables
}
