/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGO.LoginPage;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;

import finalprojectUserInterface.NGOInterface.LoginPage.NGOAdminLoginPages.AdminPageForNGOManager;
import finalprojectUserInterface.NGOInterface.LoginPage.NGOAdminLoginPages.AdminReceiveItem;
import finalprojectUserInterface.NGOInterface.LoginPage.NGOAdminLoginPages.AdminDonation;
import finalprojectUserInterface.MainJFrameForm;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author shreyas purkar
 */
public class NGOAdminLogin extends javax.swing.JPanel {

    /**
     * Creates new form NGOAdminLogin
     */
    
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    NGOClass ngo;
    

        public NGOAdminLogin(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, NGOClass h) {
        initComponents();
        this.setSize(1400, 800);
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.ngo = h;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        ManagerBtn = new javax.swing.JButton();
        ReceiveItemBtn = new javax.swing.JButton();
        DonationsBtn = new javax.swing.JButton();
        Btn_Logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelArea2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 146, 125));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(94, 80, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerBtn.setBackground(new java.awt.Color(102, 102, 102));
        ManagerBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ManagerBtn.setText("Managers");
        ManagerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ManagerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 40));

        ReceiveItemBtn.setBackground(new java.awt.Color(102, 102, 102));
        ReceiveItemBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ReceiveItemBtn.setText("Receive Item");
        ReceiveItemBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReceiveItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveItemBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ReceiveItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 40));

        DonationsBtn.setBackground(new java.awt.Color(102, 102, 102));
        DonationsBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DonationsBtn.setText("Donations");
        DonationsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DonationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonationsBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DonationsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 40));

        Btn_Logout.setBackground(new java.awt.Color(255, 102, 102));
        Btn_Logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Logout.setText("Logout");
        Btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 210, 70));

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelArea2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/wp7919585-beige-desktop-wallpapers.jpg"))); // NOI18N
        jPanel3.add(jLabelArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 800));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Admin Login");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 752, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 753, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 400, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 400, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerBtnActionPerformed
        // TODO add your handling code here:
        AdminPageForNGOManager ad = new AdminPageForNGOManager(MainLPage, dB4OUtility, operatingSystem, ngo);
        jSplitPane1.setRightComponent(ad);
    }//GEN-LAST:event_ManagerBtnActionPerformed

    private void ReceiveItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveItemBtnActionPerformed
        // TODO add your handling code here:
        AdminReceiveItem aro = new AdminReceiveItem(MainLPage, dB4OUtility, operatingSystem, ngo);
        jSplitPane1.setRightComponent(aro);
    }//GEN-LAST:event_ReceiveItemBtnActionPerformed

    private void DonationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonationsBtnActionPerformed
        // TODO add your handling code here:
        AdminDonation at = new AdminDonation(MainLPage, dB4OUtility, operatingSystem, ngo);
        jSplitPane1.setRightComponent(at);
    }//GEN-LAST:event_DonationsBtnActionPerformed

    private void Btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LogoutActionPerformed
        // TODO add your handling code here:
        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_Btn_LogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Logout;
    private javax.swing.JButton DonationsBtn;
    private javax.swing.JButton ManagerBtn;
    private javax.swing.JButton ReceiveItemBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelArea2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
